apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-gitops-rust.fullname" . }}
  labels:
    {{- include "hello-gitops-rust.labels" . | nindent 4 }}
  annotations:
    appVersion: {{ .Values.image.tag | default .Chart.AppVersion }}
spec:
  revisionHistoryLimit: 1
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hello-gitops-rust.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        appVersion: {{ .Values.image.tag | default .Chart.AppVersion }}
      {{- end }}
      labels:
        {{- include "hello-gitops-rust.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
