apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-gitops-rust.fullname" . }}
  labels:
    {{- include "hello-gitops-rust.labels" . | nindent 4 }}
  annotations:
    appVersion: {{ .Values.image.tag | default .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "hello-gitops-rust.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
